version: '3.5'
services:
    nginx: 
        image: nginx:1.17.9-alpine
        container_name: nginx
        ports:
            - 80:80
        logging:
            driver: fluentd
        depends_on:
            - fluent-bit

    fluent-bit:
        image: amazon/aws-for-fluent-bit:2.2.0
        container_name: fluent-bit
        ports:
            - 24224:24224
        volumes:
            - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
        environment:
            - AWS_ACCESS_KEY_ID='FAKE_VALUE'
            - AWS_SECRET_ACCESS_KEY='FAKE_VALUE'


